### ISSUE TITLE
Raid cursor does not work correctly

### ISSUE THREAD

**Issue by Poyasnil** [leoaviana/ConsolePortLK#1]
The function does not work correctly,

1. the cursor turns on only after pressing the hotkey + dpad up or down
2. The cursor does not turn off after pressing the hotkey and dpad remains blocked by it
3. No actions are performed on the cursor target

I really look forward to the fix, thank you for the work you have done, I have been waiting for this port on 335 for a long time

**Comment by leoaviana** [comment]
Yeah I believe I've never tested this feature... i'll take a look on it by next week because of school.

**Comment by leoaviana** [comment]
Fixed in the [1.1.0 release](https://github.com/leoaviana/WoWmapperX/releases/tag/1.1.0), sorry for the long delay.
