### ISSUE TITLE
Unsure

### ISSUE THREAD

**Issue by Primordial808** [leoaviana/ConsolePortLK#3]
Unsure if this or wowmapper but the sticks work when setting up but then i try to click on use recommended for the buttons and it doesnt do it correctly? Doing this on ascension and unsure how to proceed.

**Comment by Primordial808** [comment]
![image](https://github.com/user-attachments/assets/6758f204-7366-47cf-8695-82ad79fc56b0)
image shows this, the sticks work correctly, wowmapper is detecting ascension now but it wont let me click this button

**Comment by Primordial808** [comment]
![image](https://github.com/user-attachments/assets/d0e743d1-abcc-4838-b3c8-fd2397c11045)
alternively i get to this screen but cannot input anything

**Comment by ItsGyorg** [comment]
I am also having this issue.

**Comment by leoaviana** [comment]
Ascension is a custom client, it has major changes on the standard WoW API and it's expected to be problematic, however I did some workarounds to make it work on the [1.1.0 release.](https://github.com/leoaviana/WoWmapperX/releases/tag/1.1.0)
